### ISSUE TITLE
Testem Chrome Timeouts

### ISSUE THREAD

**Issue by patocallaghan** [testem/testem#1021]
Hey, 

as I mention in https://github.com/testem/testem/issues/1015 we frequently get testem failures in CI when running against the Chrome (we use Testem through Ember CLI). Our test runs either fail to start (as if testem can't find the browser) or fail to finish (all tests have run and pass, but the browser window sits there and it eventually times out). It usually just tells us `testem.js has not loaded`.

As the issue is intermittent it can be hard to reproduce. I've tried to recreate it in a repo by simply [forking Travis CI's web repo](https://github.com/patocallaghan/travis-web/tree/ember-exam) (uses Ember CLI) and adding `ember-exam` to it (Ember Exam just allows you to easily use Testem's parallel feature). If running a single test run it'd probably take some time to get a timeout, but if you run `ember exam --split=9 --parallel` you should start getting some timeouts in a few runs.

I've generated some (pretty verbose) logs [here](https://gist.githubusercontent.com/patocallaghan/8cc79eeaac9a3377f44840dec15391c0/raw/1a6ab68b78217cd41ced2e52d4439b529f945cc9/gistfile1.txt).

Generally on startup I've seen the following errors:

```
not ok 323 Chrome - error
    ---
        message: >
            Error: Browser failed to connect within 30s. testem.js not loaded?
            Stderr:
             2016-11-19 00:42:01.877 Google Chrome[28575:622538] NSWindow warning: adding an unknown subview: <FullSizeContentView: 0x7fa45b8022a0>. Break on NSLog to debug.
            2016-11-19 00:42:01.878 Google Chrome[28575:622538] Call stack:
            (
                "+callStackSymbols disabled for performance reasons"
            )


        Log: |
            { type: 'error',
              text: 'Error: Browser failed to connect within 30s. testem.js not loaded?' }
            { type: 'error',
              text: '2016-11-19 00:42:01.877 Google Chrome[28575:622538] NSWindow warning: adding an unknown subview: <FullSizeContentView: 0x7fa45b8022a0>. Break on NSLog to debug.\n2016-11-19 00:42:01.878 Google Chrome[28575:622538] Call stack:\n(\n    "+callStackSymbols disabled for performance reasons"\n)\n' }
    ...
```

On timeouts at the end I've seen

```
  engine:ws writing "3" +1ms
  engine:polling closing +649ms
  engine:polling transport not writable - buffering orderly close +0ms
  socket.io:client client close with reason ping timeout +0ms
  socket.io:socket closing socket - reason ping timeout +0ms
  engine:polling closing +8ms
  engine:polling transport not writable - buffering orderly close +1ms
  socket.io:client client close with reason ping timeout +0ms
  socket.io:socket closing socket - reason ping timeout +0ms
  engine:polling closing +654ms
  engine:polling transport not writable - buffering orderly close +0ms
  socket.io:client client close with reason ping timeout +0ms
  socket.io:socket closing socket - reason ping timeout +0ms
  engine:polling closing +78ms
  engine:polling transport not writable - buffering orderly close +0ms
  socket.io:client client close with reason ping timeout +0ms
  socket.io:socket closing socket - reason ping timeout +0ms
  engine:polling closing +5s
  engine:polling transport not writable - buffering orderly close +0ms
  socket.io:client client close with reason ping timeout +0ms
  socket.io:socket closing socket - reason ping timeout +0ms
  engine:polling closing +2s
  engine:polling transport not writable - buffering orderly close +0ms
  socket.io:client client close with reason ping timeout +0ms
  socket.io:socket closing socket - reason ping timeout +0ms
not ok 205 Chrome - error
    ---
        message: >
            Error: Browser disconnected
            Stderr:
             2016-11-19 00:49:10.060 Google Chrome[28965:629220] NSWindow warning: adding an unknown subview: <FullSizeContentView: 0x7fa7a07af8a0>. Break on NSLog to debug.
            2016-11-19 00:49:10.061 Google Chrome[28965:629220] Call stack:
            (
                "+callStackSymbols disabled for performance reasons"
            )


        Log: |
            { type: 'error', text: 'Error: Browser disconnected' }
            { type: 'error',
              text: '2016-11-19 00:49:10.060 Google Chrome[28965:629220] NSWindow warning: adding an unknown subview: <FullSizeContentView: 0x7fa7a07af8a0>. Break on NSLog to debug.\n2016-11-19 00:49:10.061 Google Chrome[28965:629220] Call stack:\n(\n    "+callStackSymbols disabled for performance reasons"\n)\n' }
    ...
  socket.io:client client close with reason transport close +8s
  socket.io:socket closing socket - reason transport close +0ms
```

Other things to note:
* we've been experiencing this for a while now, through multiple versions of Chrome, Node and Testem. Currently running latest Chrome, Testem 1.13 and Node 7.
* We have a large codebase (~150K LOC) so not sure if that amplifies the issue or not. 

/cc @stefanpenner (as we chatted briefly about this)

**Comment by johanneswuerbach** [comment]
@patocallaghan first thing after looking into your repo, are you sure each browser instance starts in < 30s? This is the default start timeout and it was causing a bunch of browsers to fail for me.

You can tweak this in your config `browser_start_timeout`  https://github.com/testem/testem/blob/master/docs/config_file.md#config-level-options

**Comment by johanneswuerbach** [comment]
Once testem successfully started, it should always close and I would consider this a bug, but can't really reproduce it yet :-(

**Comment by patocallaghan** [comment]
@johanneswuerbach tried what you suggested with increasing the browser startup timeout but it didn't work. I'm still getting testem failing to start.

With regards this error here:

```
not ok 1 Browser "google-chrome --user-data-dir=/tmp/testem-2441 --no-default-browser-check --no-first-run --ignore-certificate-errors --test-type --disable-renderer-backgrounding --disable-background-timer-throttling http://localhost:7357/2441/tests/index.html?hidepassed&filter=team%20observe%20%7C" failed to connect. testem.js not loaded?
```

where would this be thrown from? I can't find any string in the codebase that matches `failed to connect. testem.js not loaded?`

**Comment by patocallaghan** [comment]
@johanneswuerbach so I tried to look a little bit more into it and I saw the below error

```
not ok 1 Chrome - error
    ---
        message: >
            Error: Browser failed to connect within 60s. testem.js not loaded? HELLO
            Stderr:
             [58095:58095:1124/113207:ERROR:browser_main_loop.cc(261)] Gtk: Locale not supported by C library.
                Using the fallback 'C' locale.
            Xlib:  extension "RANDR" missing on display ":99".
            Xlib:  extension "RANDR" missing on display ":99".
            [58095:58118:1124/113207:ERROR:proxy_service_factory.cc(128)] Cannot use V8 Proxy resolver in single process mode.
            [58095:58118:1124/113207:ERROR:proxy_service_factory.cc(128)] Cannot use V8 Proxy resolver in single process mode.


        Log: |
            { type: 'error',
              text: 'Error: Browser failed to connect within 60s. testem.js not loaded? HELLO' }
            { type: 'error',
              text: '[58095:58095:1124/113207:ERROR:browser_main_loop.cc(261)] Gtk: Locale not supported by C library.\n\tUsing the fallback \'C\' locale.\nXlib:  extension "RANDR"missing on display ":99".\nXlib:  extension "RANDR" missing on display ":99".\n[58095:58118:1124/113207:ERROR:proxy_service_factory.cc(128)] Cannot use V8 Proxy resolver in single process mode.\n[58095:58118:1124/113207:ERROR:proxy_service_factory.cc(128)] Cannot use V8 Proxy resolver in single process mode.\n' }
    ...
```

I'm not sure about the Chrome error itself but interestingly Testem hung after this was thrown and didn't automatically close. It stayed open indefinitely. I wonder is there some codepath being exercised when this type of error his hit where it doesn't close the process?

**Comment by avdv** [comment]
Hi.

We have the same problem. Chrome just open the window and the tab spinner is running, but it seems it cannot load the page from localhost:33062/921/tests/index.html. We're using ember-cli too.

We have set the timeout to 180 seconds, but still no dice. :sob: 

Firefox on the other hand just works, but Chrome starts only 1/50 times. Chrome only show the `Xlib: extension "RANDR" missing on display warning` message.

I used x11vnc to have a look at the Xvfb display via SSH, and now chrome immediately displays the "Aw Snap, something went wrong while loading the page" error message. I've tried version 54 and 55.

When I reload the page and open the devtools, I can see that loading the 10.6 MiB resources of the page takes 2.5 minutes to finish (whereas firefox only takes a few seconds). So, after setting the timeout to ridiculous 300 seconds, chrome actually starts to run the tests...

**Comment by johanneswuerbach** [comment]
Could you inspect the network traffic, whether some websocket traffic is done during that time? Maybe testem client / server are in an endless loop for some reason.

**Comment by cs3b** [comment]
I've the same issue with Firefox ... and it only is a problem in Travis CI (not sure why), locally works fine, here are the logs from Travis Ci

````
$ export DISPLAY=:99.0

$ sh -e /etc/init.d/xvfb start
Starting virtual X frame buffer: Xvfb.

$ sleep 3

$ firefox --version
Mozilla Firefox 53.0a2

$ node_modules/ember-cli/bin/ember test
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
Building
cleaning up
cleaning up...
Built project successfully. Stored in "/home/travis/build/Selleo/selleo-mail-log/tmp/core_object-tests_dist-MidNYxQe.tmp".
not ok 1 Firefox - error
    ---
        message: >
            Error: Browser failed to connect within 300s. testem.js not loaded?
            Stderr: 
             ExceptionHandler::GenerateDump cloned child 3172
            ExceptionHandler::SendContinueSignalToChild sent continue signal to child
            ExceptionHandler::WaitForContinueSignal waiting for continue signal...
            
            
        Log: |
            { type: 'error',
              text: 'Error: Browser failed to connect within 300s. testem.js not loaded?' }
            { type: 'error',
              text: 'ExceptionHandler::GenerateDump cloned child 3172\nExceptionHandler::SendContinueSignalToChild sent continue signal to child\nExceptionHandler::WaitForContinueSignal waiting for continue signal...\n' }
    ...
````

and here is the travis ci config

````


{
  "language": "node_js",
  "node_js": "6",
  "env": "CXX=g++-4.8",
  "addons": {
    "apt": {
      "sources": [
        "ubuntu-toolchain-r-test"
      ],
      "packages": [
        "g++-4.8"
      ]
    },
    "firefox": "latest-dev"
  },
  "sudo": false,
  "cache": {
    "directories": [
      "$HOME/.npm",
      "$HOME/.yarn-cache",
      "$HOME/.cache"
    ]
  },
  "before_install": [
    "npm config set spin false",
    "npm install -g yarn"
  ],
  "install": [
    "yarn install",
    "node_modules/bower/bin/bower install"
  ],
  "before_script": [
    "export DISPLAY=:99.0",
    "sh -e /etc/init.d/xvfb start",
    "sleep 3",
    "firefox --version"
  ],
  "script": [
    "node_modules/ember-cli/bin/ember test"
  ],
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}

````

might be that the problem is within travis ci itself - still hard to debug. So far the only solutions is to go back to PhantomJS.

**Comment by YoranBrondsema** [comment]
@patocallaghan Have you had any luck fixing this? Or any new information that came up? We're seeing the same issues (tests won't start about 1/2 of the time, on Chrome) and it's really hampering productivity as you can imagine.

1. It happens more often that the test do not start all, with the `Browser failed to connect within 30s. testem.js not loaded?` message
2. It happens that the tests hang at the end, despite having run them all. But this happens only occasionally so I'd rather focus on 1.

I'm really trying to get this fixed but it's not easy as we use Codeship as CI so we don't control the environment, and it doesn't always happen. Most fun bugs... :( So anything new that you discovered would be welcome!

**Comment by ghempton** [comment]
This same issue happens for us on CircleCI. About 1/10 builds fail to launch with `Browser failed to connect within 30s. testem.js not loaded`.

**Comment by johanneswuerbach** [comment]
I didn't had any luck tracking this down yet, especially as this mainly happens only on CI and isn't really reliable reproducable.

Hopefully chrome headless https://www.chromestatus.com/features/5678767817097216 will bring together with remote debugging better debugging in those environments

**Comment by manimis902** [comment]
We are seeing similar issues with our Team City build server.
The error message is slightly different though.

```
[Chrome - error] Error: Browser failed to connect within 30s. testem.js not loaded?
Stderr: 
 [0419/061938.039012:WARNING:audio_manager.cc(321)] Multiple instances of AudioManager detected
[0419/061938.039065:WARNING:audio_manager.cc(278)] Multiple instances of AudioManager detected
[0419/061938.371223:ERROR:socket_posix.cc(126)] bind() returned an error, errno=98: Address already in use
[0419/061938.371271:ERROR:devtools_http_handler.cc(221)] Cannot start http server for devtools. Stop devtools.
```

**Comment by johanneswuerbach** [comment]
It would be great to get the chrome debug console output in those cases, maybe using the remote debugger are somehow manually.

Looks like in some cases the initial connect takes >30s with can have multiple reasons: unparsable js, slow js parsing, failed websocket, testem client bug, etc.

Sadly there isn't much, which can be done before connecting (as there is obviously no connection), but maybe the remote debug protocol could provide some access to the console output

**Comment by YoranBrondsema** [comment]
@manimis902 Are you running headless Chrome? In that case, your error might be an issue in Chrome itself (see https://bugs.chromium.org/p/chromium/issues/detail?id=678948).

**Comment by manimis902** [comment]
@YoranBrondsema  Yes we are using chrome headless. I landed on the chromium issue while debugging , although for time being, we solved the failures by increasing ```browser_start_timeout``` to 150s.

FYI, our test suite runs in 24 partitions.

**Comment by johanneswuerbach** [comment]
@YoranBrondsema do you also run all 24 partitions in parallel? That might be explaining why spawning the 24 instances is taking some time.

**Comment by YoranBrondsema** [comment]
@johanneswuerbach I run 2 partitions in parallel but they are run on 2 separate VMs on Codeship. So only one instance is started on each VM.

**Comment by knownasilya** [comment]
Having a similar issue, if I increase the browser timeout, I get this error.

> Error: Browser exited unexpectedlyNon-zero exit code: 1[eval("(function(undefined) {window.jasmine && (JSTestingReport
erSL = (function(undefined) {\n\n  return function() {\n    return {\n      failedCount: jasmine.currentEnv_.currentRu
nner_.results().failedCount\n    };\n  }\n\n})());\n\nwindow.mocha && (JSTestingReporterSL = (function(undefined) {\n\
n  function hasArray(obj, nameArray) {\n    return obj && obj[nameArray] && obj[nameArray].length > 0;\n  }\n\n  funct
ion hasSuite(obj) {\n    return hasArray(obj, \"suites\");\n  }\n\n  function hasSpec(obj){\n    return hasArray(obj,
\"tests\");\n  }\n\n  function reporterSpec(test) {\n    var isPassed = test.state === \"passed\";\n    return {\n
  description : test.title,\n      durationSec : test.duration/1000,\n      passed      : isPassed,\n      passedCount
 : isPassed ? 1 : 0,\n      failedCount : isPassed ? 0 : 1,\n      totalCount  : 1\n    };\n  }\n\n  function emptyRep
orter() {\n    return {\n      description : \"\",\n      durationSec : 0,\n      passed      : true,\n      totalCoun
t  : 0\n    };\n  }\n\n  function reporterObjects(objs, fn) {\n    var reporter = emptyReporter();\n    reporter.resul
t = [];\n\n    for (var i=0; i<objs.length; i++) {\n      var obj = fn(objs[i]);\n      reporter.durationSec += obj.du
rationSec ? obj.durationSec : 0;\n      reporter.totalCount  += obj.totalCount;\n      reporter.passed = reporter.pass
ed && obj.passed;\n      reporter.result.push(obj);\n    }\n\n    return reporter;\n  }\n\n  function reporterSpecs(te
sts) {\n    return reporterObjects(tests, reporterSpec);\n  }\n\n  function reporterSuites(suites) {\n    return repor
terObjects(suites, reporterSuite);\n  }\n\n  function reporterSuite(suite) {\n    var specs  = hasSpec(suite)  ? repor
terSpecs(suite.tests)   : emptyReporter(),\n        suites = hasSuite(suite) ? reporterSuites(suite.suites) : emptyRep
orter();\n\n    return {\n      description : suite.title,\n      specs       : specs.result || [],\n      suites
 : suites.result || [],\n      durationSec : specs.durationSec + suites.durationSec,\n      totalCount  : specs.totalC
ount + suites.totalCount,\n      passed      : specs.passed && suites.passed\n    };\n  }\n\n  return function() {\n

I'm using ember-cli-sauce.

**Comment by derekdowling** [comment]
@mani-mishra I'm seeing the same error output as you running:
```
launch_in_ci: [ 'Chrome' ],
browser_args: {
  Chrome: [ '--headless', '--disable-gpu', '--remote-debugging-port=9222', '--no-sandbox'] 
}
```

**Comment by briangonzalez** [comment]
@derekdowling @knownasilya Any luck on your end? We're seeing this, too.

**Comment by knownasilya** [comment]
No improvements here, unfortunately.

**Comment by stephanebruckert** [comment]
I remember having subscribed to that thread and this issue was pretty annoying. On the same project I am not having any issues anymore though. I am going to share few elements of my local + codeship (hopefully equivalent to Travis) configs:

### Local

```
✗ node -v 
v7.9.0
✗ phantomjs -v
2.1.1
```
`ember test
`

### Travis

```
nvm install 7.9.0
npm install -g bower@1.8.0
npm install -g phantomjs-prebuilt
npm install
bower install
```

`ember test
`
### Common

#### testem.js

```
/* eslint-env node */

module.exports = {
  "test_page": "tests/index.html?hidepassed",
  "disable_watching": true,
  "launchers": {
    "AltPhantom": {
      "exe": "phantomjs",
      "args": ["tests/phantom-runner.js"],
      "protocol": "browser"
    }
  },
  "launch_in_ci": [
    "AltPhantom"
  ],
  "launch_in_dev": [
    "AltPhantom",
    "Firefox",
    "Chrome",
    "Safari"
  ]
};
```

#### tests/phantom-runner.js

```
/* eslint-disable */

// Custom version of the Testem PhantomJS runner.
//   This exists to block requests to fonts.googleapis.com because this can cause
//     Phantom to incompletely load JS files causing bizarre syntax errors.
//   See https://github.com/ariya/phantomjs/issues/14173.

var system = require('system');
var webpage = require('webpage');
var page = webpage.create();

var url = system.args[1];
page.viewportSize = {
  width: 1024,
  height: 768
};

// The magic!
page.onResourceRequested = function(requestData, networkRequest) {
  if (requestData.url.match('fonts.googleapis.com')) {
    networkRequest.abort();
  }
};
page.open(url);
```

^ this file magically fixed other random PhantomJS/testem issues.

Please try

**Comment by lolmaus** [comment]
@vitkhab has discovered that migrating to [this](https://github.com/mark-adams/docker-chromium-xvfb) Docker container resolves the issue. Notice this item on their methodology:

> 3. Traps SIGTERM and relays the signal to the browser and Xvfb so that they will not continue to run once the test runner is finished. This is mostly required to deal with Karma's insistence that the browser process be terminated before it can exit. Without this relaying, Karma would hang indefinitely.

**Comment by jonathanong** [comment]
a bigger issue for me is that when i get this error, testem does not exit the process. my CI build ends up hanging. is this a known issue? i don't mind retrying my test if i get this type of error

**Comment by bricss** [comment]
This how I fixed timeout issue with Chrome 59+:
```json
{
    "framework": "qunit",
    "test_page": "tests/index.html?hidepassed",
    "disable_watching": true,
    "launch_in_ci": [
        "Chrome"
    ],
    "launch_in_dev": [
        "Chrome"
    ],
    "browser_start_timeout": 60,
    "browser_args": {
        "Chrome": [
            "--disable-web-security",
            "--disable-gpu",
            "--headless",
            "--incognito",
            "--no-sandbox",
            "--remote-debugging-address=0.0.0.0",
            "--remote-debugging-port=9222"
        ]
    }
}
```

**Comment by stephanebruckert** [comment]
@bricss' fix seems to work!

**Comment by lolmaus** [comment]
We're seeing `Error: Browser disconnected` in our Ember tests and the above does not help. :sob: Different issue?

**Comment by bricss** [comment]
@lolmaus Chrome 60 was released today, try it. 🤓

**Comment by lolmaus** [comment]
Our errros were caused by our Ember app leaving `/tests` after an Ember Data upgrade. There's still something fishy, but at least it's not related to Testem.

**Comment by avdv** [comment]
Using Chome 59 in headless mode works for us too. Our config:

```
"browser_args": {
      "Chrome": [
        "--headless",
        "--disable-gpu",
        "--remote-debugging-port=0"
      ]
    }
```

**Comment by QuantumInformation** [comment]
@avdv no luck with that chrome 59 or 60

**Comment by josemarluedke** [comment]
Hey @lolmaus. What did you do to solve the errors in Ember Data you mentioned?

**Comment by briangonzalez** [comment]
You can set your router location to `none` in testing. I've done this before with success.

**Comment by ahmetemrekilinc** [comment]
@bricss thank you, this worked perfectly :)

**Comment by rstudner** [comment]
So i'm running tests inside a docker container on CircleCI.

I get Browser Disconnected on my LAST test which fails the build.

Have tried all of the above configs :)

**Comment by larsklevan** [comment]
Check out this comment on #777 re: increasing `shm_size` in Docker containers to prevent sporadic Chrome crashes. May help:
https://github.com/testem/testem/issues/777#issuecomment-338516811

**Comment by scottkidder** [comment]
I have had success working around `Error: Browser disconnected` by setting `browser_disconnect_timeout: 120` !

In my case, I am using [ember-visual-test](https://github.com/Cropster/ember-visual-test) and I think testem is monitoring the headless chrome that is started, used to screenshot, and then cleanly shutdown by the addon.

**Comment by scalvert** [comment]
We're seeing this issue quite often in our test suite. our Ember app has about ~18000 tests, and we use ember-exam to split and run those tests in partitions. I'm curious how large other people's test suites are, as I'm looking to gauge the threshold at which this issue present itself.

**Comment by lrdiv** [comment]
@scalvert I only have about 250 tests (including ESLint) but I need to create a lot of data using mirage. Just started running into this today

**Comment by JonForest** [comment]
@scalvert we have about 350 tests, but it seems to fail at a random point in them.  Increasing the timeout to 120 did not help us either.
The frustrating thing is it never seems to happen locally, only in CI.

**Comment by jiangty-addepar** [comment]
We're having a similar problem with our Ember tests, but I'm not sure it's quite the same.

Sometimes, when a test fails in one of our test shards (~500 tests in a test shard), tests just hang forever. We don't see anything like `"Error: browser disconnected"`; just a failed test, and then no output until Jenkins kills the process for timing out.

**Comment by step2yeung** [comment]
Our theory was some of our tests is blocking the main thread for some period of time. When such a test is executing, while the socket.io's heartbeat is waiting for a reply, it could cause the socket to disconnect since a reply for the heartbeat does not reach the socket in time.
The socket disconnecting will emit a disconnect event, which testem handles in `ondisconnect()`, and waits for `browser_disconnect_timeout` amount of time until throwing `Browser Timeout Exceeded` error.

After submitting #1248 , which makes socketio's heartbeat timeout configurable in testem's config. We set the heartbeat timeout to a value larger than 5s (which is the default timeout value socketio sets) and have yet to see a test run failing for browser timeout.

**Comment by stefanpenner** [comment]
> After submitting #1248 , which makes socketio's heartbeat timeout configurable in testem's config. We set the heartbeat timeout to a value larger than 5s (which is the default timeout value socketio sets) and have seen an improvement although not totally eliminating the timeouts.

Should we increase the heartbeat timeout, automatically when the primary timeout config is changed? Something like 80% the primary timeout, unless the heartbeat timeout has its own config?

**Comment by astronomersiva** [comment]
@step2yeung , can confirm this. I am yet to see a failure after trying this out. Will see if there are any failures over the coming days.

I have set it equal to the browser timeout itself to be on the safe side. I believe @stefanpenner's idea is correct. We should be setting this automatically based on the browser timeout. I can work on it if you guys are okay with it.

**Comment by step2yeung** [comment]
+1 to @stefanpenner suggestion
@astronomersiva I am totally open to that :)

**Comment by astronomersiva** [comment]
> Should we increase the heartbeat timeout, automatically when the primary timeout config is changed? Something like 80% the primary timeout, unless the heartbeat timeout has its own config?

Merged in #1252 .

**Comment by lolmaus** [comment]
Any luck with this?

I'm on latest Testem (2.8.0 which incorporates #1252), set the `browser_disconnect_timeout` to `200`, still crashes with: 

```
not ok 2212 Chrome - error
    ---
        message: >
            Error: Browser timeout exceeded: 200s
            Error while executing test: ESLint | mirage: mirage/config.js
            Stderr: 
             [0619/093644.920634:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.
```

The file mentioned is lint-free and each time it crashes on a different test.

Please help, we can't deploy due to this.

**Comment by lolmaus** [comment]
Ok, I've noticed that each increase of `browser_disconnect_timeout ` moves the crash further in the log. So I've increased `browser_disconnect_timeout` to a whopping `500` and it finally passed.

There's something fishy there, looks like that in order to pass this timeout has to be as large as the whole test suite takes. Which makes no sense to me.

**Comment by bryanaka** [comment]
I am having the same issue as @lolmaus when upgrading from 1.13.X to 2.4 Using Ember CLI 2.11.0 (I don't know why, but someone upgraded it separately from me and the ember version).

I think this might be related to some recursive timers in my app but no way to fact check that without going through a lot of tests and skipping until one works.

**Comment by stefanpenner** [comment]
@lolmaus  / @bryanaka what test framework (qunit/mocha etc) and which version of said framework are you using?

**Comment by stefanpenner** [comment]
@lolmaus to answer your earlier question "any luck with this", the answer is yes. Speaking with @step2yeung today, one of our super massive test suites using ember/qunit/testem now has only exhibited 1 Browser Disconnect for about 2000 test runs on our CI infrastructure, where previously it was much much much worse.

Maybe @step2yeung can give a better summary, but I believe TL;DR has been:

* fixes to testem temp-dir
* tweaking heartbeat timeouts
* misc other testem fixes

**Comment by bryanaka** [comment]
Thanks for your help on this @stefanpenner - let me know if you need any other information. I am going to spend time tomorrow tracking down what tests may be at the root of this and see if I can produce a minimal reproducible test suite. 

```js
// testem.js

const BROWSER_ARGS = {
    Chrome: {
      mode: 'ci',
      args: [
        '--disable-gpu',
        '--headless',
        '--remote-debugging-port=0',
        '--window-size=1440,900',
        '--ignore-certificate-errors'
      ]
    }
}

if (process.env.CIRCLECI || process.env.CI) {
  BROWSER_ARGS['Chrome'].args.push('--no-sandbox');
}

module.exports = {
  framework: "qunit",
  test_page: "tests/index.html?hidepassed",
  disable_watching: true,
  reporter: "dot",
  browser_disconnect_timeout: 500,
  launch_in_ci: [
    'Chrome'
  ],
  launch_in_dev: [
    'Chrome'
  ],
  browser_args: BROWSER_ARGS
  }
};
```

**Comment by lolmaus** [comment]
@stefanpenner We're on QUnit.

* ember-qunit: version "3.1.0"
* qunit: version "2.4.1"
* ember-cli-qunit: version "4.1.1"
* ember-cli: version "2.17.1"

We've planned Ember CLI upgrade to the next milestone, but both current and next milestones are gonna take a while.

The issue random test failures seems to be systematic. I've seen it for years on many different projects (including freshly created addons), different test suites (both QUnit and Mocha), different CI platforms (CodeShip, Travis, Jenkins).

Reducing the frequency of random failures is an achievement, but it's not a solution. :( Especially when we have to bump timeouts up to a point where they no longer make sense.

**Comment by step2yeung** [comment]
As @stefanpenner said, since landing the fixes listed above, we so far have only saw 1 instance in almost 2 weeks, compared to ~5% of runs daily before the fixes.

We have:
- ember-qunit: version "2.2.0"
- qunit: version "2.4.1"
- ember-cli-qunit: version "3.1.2"
- ember-cli: version "3.0.1"

Our test suite setup has multiple machines running different set of tests using ember exam with multiple splits, so #1257 helped with making sure no repeated launcherId is used.

#1268 and #1248 both helped with relaxing the time configured to socketio to timeout of it doesn't receive heartbeat message, since it seems some of our tests does block the main thread for longer than the default time of 5 seconds.

Two things we observed that can also cause browser disconnects is infinite loops in app code, as well as alert/confirm dialogs. I will be creating a PR to replace alert/confirm globals with methods that throw if accessed.

@lolmaus it would be useful to add `<script>localStorage.debug='*';</script>` to your test/index.html to generate debug logs from socketio to understand whether it is socket.io that is causing this timeout to occur.

**Comment by stefanpenner** [comment]
@lolmaus unfortunately, the version of ember-cli you are is using a 1.x series Testem, which doesn't have the fixes mentioned above.

ember-cli@v2.17.1 depends on v1.x -> https://github.com/ember-cli/ember-cli/blob/v2.17.2/package.json#L116
ember-cli@v2.18.2 depends on v2.x -> https://github.com/ember-cli/ember-cli/blob/v2.18.2/package.json#L116

I would encourage you to upgrade ember-cli, now you don't need to upgrade all the dependencies, I believe simply upgrading ember-cli itself should be sufficient. Ember-cli aims to be compatible with all versions of ember etc, and for the most part all addons respect that. Please give that a try, and report back.

**Comment by stefanpenner** [comment]
@bryanaka the same advice to you, ember-cli 2.11.x is pined to a very old version of testem, which doesn't include the fixes put out by @step2yeung and friends.

That nice thing is, ember-cli can be upgraded independently of ember/ember-data etc, and should be relatively painless.

**Comment by stefanpenner** [comment]
Of people with the above problem, who is in the latest testem (2.8.2)

**Comment by bryanaka** [comment]
Upgrading to Ember CLI 2.18.X did not help, still the same issue :(

Ember CLI Qunit: 3.1.3
Qunit: 2.6.1
Ember Qunit: 2.0.0-Beta

I am going to try to upgrade Ember QUnit to 3.X

**Comment by stefanpenner** [comment]
> Upgrading to Ember CLI 2.18.X did not help, still the same issue :(

Bummer, at-least stuff is more up 2 date. Could you confirm with my what version of testem you are now on?

**Comment by stefanpenner** [comment]
@bryanaka  one idea on linux that help us was to run with the following chrome flag`--disable-dev-shm-usage` flag. This addresses some old kernel + chrome related sadness.

**Comment by stefanpenner** [comment]
> @lolmaus it would be useful to add <script>localStorage.debug='*';</script> to your test/index.html to generate debug logs from socketio to understand whether it is socket.io that is causing this timeout to occur.

@bryanaka  ^

**Comment by stefanpenner** [comment]
some potential improvements to default chrome-runner config.. https://github.com/ember-cli/ember-cli/pull/7879

**Comment by lolmaus** [comment]
Still having errors like this:

```
ok 2207 Chrome 66.0 - Exam Partition 5 - Acceptance | Repository Settings: disabling `Enforce approval reset` setting
not ok 2208 Chrome - error
    ---
        message: >
            Error: Browser timeout exceeded: 500s
            Error while executing test: ESLint | mirage: mirage/config.js
            Stderr: 
             [0621/150310.773871:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.
```

I've been watching build, it stalled for a few minutes before spitting out that error. Doesn't look like increasing the timeout further can help.

Here's the error with the socket.io debug output: https://gist.github.com/lolmaus/2f04ce1f704d7cd645c557ff87824b2e

@step2yeung @stefanpenner Do you see any clues in that log?

**Comment by bryanaka** [comment]
@stefanpenner Still no luck :(

```
// testem.js

module.exports = {
  framework: "qunit",
  test_page: "tests/index.html?hidepassed",
  disable_watching: true,
  reporter: "dot",
  browser_disconnect_timeout: 500,
  launch_in_ci: [
    'Chrome'
  ],
  launch_in_dev: [
    'Chrome'
  ],
  browser_args: {
    Chrome: {
      mode: 'ci',
      args: [
        '--disable-gpu',
        '--headless',
        '--disable-dev-shm-usage',
        '--disable-software-rasterizer',
        '--mute-audio',
        '--remote-debugging-port=0',
        '--window-size=1440,900',
        '--ignore-certificate-errors',
        '--no-sandbox'
      ]
    }
  }
};
```

Debug Logs: https://gist.github.com/bryanaka/de421be31785df1cd24b0f898386a66c

**Comment by bryanaka** [comment]
Tests pass locally on MacOS, just fail in Linux in Circle CI using the `node/boron-browsers` container

**Comment by step2yeung** [comment]
@lolmaus from the logs, I am seeing Partition 8 completes its execution, shown by the `after-tests-complete` and `all-test-results` events. 
```
[0621/161708.236830:INFO:CONSOLE(6)] "%csocket.io-parser %cencoding packet {"type":2,"data":["test-result",{"id":31,"name":"Exam Partition 8 - Markdown | Renderer: render method","items":[{"passed":true,"message":"should render nothing if renderer is not prepared"},{"passed":true,"message":"should render markdown"}],"failed":0,"passed":2,"skipped":false,"total":2,"runDuration":293}],"options":{"compress":true},"nsp":"/"}%c +294ms", source: http://localhost:7357/socket.io/socket.io.js (6)
            [0621/161708.237476:INFO:CONSOLE(6)] "%csocket.io-parser %cencoded {"type":2,"data":["test-result",{"id":31,"name":"Exam Partition 8 - Markdown | Renderer: render method","items":[{"passed":true,"message":"should render nothing if renderer is not prepared"},{"passed":true,"message":"should render markdown"}],"failed":0,"passed":2,"skipped":false,"total":2,"runDuration":293}],"options":{"compress":true},"nsp":"/"} as %s%c +0ms", source: http://localhost:7357/socket.io/socket.io.js (6)
            [0621/161708.237772:INFO:CONSOLE(6)] "%csocket.io-client:manager %cwriting packet {"type":2,"data":["after-tests-complete"],"options":{"compress":true},"nsp":"/"}%c +2ms", source: http://localhost:7357/socket.io/socket.io.js (6)
            [0621/161708.240805:INFO:CONSOLE(6)] "%csocket.io-parser %cencoding packet {"type":2,"data":["after-tests-complete"],"options":{"compress":true},"nsp":"/"}%c +5ms", source: http://localhost:7357/socket.io/socket.io.js (6)
            [0621/161708.240856:INFO:CONSOLE(6)] "%csocket.io-parser %cencoded {"type":2,"data":["after-tests-complete"],"options":{"compress":true},"nsp":"/"} as %s%c +0ms", source: http://localhost:7357/socket.io/socket.io.js (6)
            [0621/161708.241303:INFO:CONSOLE(6)] "%csocket.io-client:manager %cwriting packet {"type":2,"data":["all-test-results"],"options":{"compress":true},"nsp":"/"}%c +3ms", source: http://localhost:7357/socket.io/socket.io.js (6)
            [0621/161708.241410:INFO:CONSOLE(6)] "%csocket.io-parser %cencoding packet {"type":2,"data":["all-test-results"],"options":{"compress":true},"nsp":"/"}%c +0ms", source: http://localhost:7357/socket.io/socket.io.js (6)
            [0621/161708.241683:INFO:CONSOLE(6)] "%csocket.io-parser %cencoded {"type":2,"data":["all-test-results"],"options":{"compress":true},"nsp":"/"} as %s%c +0ms", source: http://localhost:7357/socket.io/socket.io.js (6)
```
right after that.. for some reason, the browser side socket is closed in an unexpected way it seems (i say unexpected, because socketio tries to reconnect the socket, which I never see happen when a test completes executing properly):
```
[0621/162310.473570:INFO:CONSOLE(6)] "%cengine.io-client:socket %csocket close with reason: "%s"%c +8m", source: http://localhost:7357/socket.io/socket.io.js (6)
            [0621/162310.474532:INFO:CONSOLE(6)] "%csocket.io-client:manager %conclose%c +6m", source: http://localhost:7357/socket.io/socket.io.js (6)
            [0621/162310.474572:INFO:CONSOLE(6)] "%csocket.io-client:manager %ccleanup%c +1ms", source: http://localhost:7357/socket.io/socket.io.js (6)
            [0621/162310.475354:INFO:CONSOLE(6)] "%csocket.io-client:socket %cclose (%s)%c +9m", source: http://localhost:7357/socket.io/socket.io.js (6)
            [0621/162310.476030:INFO:CONSOLE(6)] "%csocket.io-client:manager %cwill wait %dms before reconnect attempt%c +1ms", source: http://localhost:7357/socket.io/socket.io.js (6)
```
You may want to play with engineio to print out the reason it's closing the socket. Then try to understand why it isn't closing the socket properly.

**Comment by step2yeung** [comment]
@bryanaka on your logs, it doesn't look like the browser showed any problems. You may want to add `DEBUG=socket.io*,engine*` before you ember test or ember exam command to get debug logs from the server socket code. Since its possible its the server side that is closing the socket causing the timeout.

**Comment by lolmaus** [comment]
@step2yeung @stefanpenner Here are our logs with engine.io debug output enabled: https://gist.github.com/lolmaus/03e121c03573842bbd56aa4dbb135faf

Can you see the cause of the problem there?

Not sure if its relevant, but line 1824 of the log is trimmed. The filename should be `default-reviewers-listing-steps.js`, but the line starts with `fault-reviewers-listing-steps.js`.

**Comment by bryanaka** [comment]
@step2yeung @stefanpenner and here are mine with engine.io, socket.io debug output

Has two failed runs and one passing run, all run on the same commit
https://gist.github.com/bryanaka/965090f948009841ad46236007306e2a

Not sure if related: one thing I am noticing is my acceptance tests are taking quite a bit longer in Linux than in MacOS post upgrade of Ember to 2.X where as before they were about equivalent.

**Comment by step2yeung** [comment]
@lolmaus 
From your log, I can see a few things
1) from the stderr messages, it is return logs from partition 7, which seems to have finished because it emits a `all-test-results` and `after-tests-complete`. 
I experienced this as well before, which lead to fixes to the launcher ids: #1257
The issue was launcherIds is being repeated. eg. partition 1 and partition 7 both have the same partition number. You can find this out by outputing the testem socketio server debug logs (with `DEBUG=socket.io:socket` and looking for `socket.io:socket emitting event ["browser-login","Chrome 67.0",`
The last value is the launcherId. If you see a repeat, that would mean #1257 may still not be generating unique launcherIds.

2) I also see some 
```
2018-06-22T10:59:29.256Z engine:polling transport not writable - buffering orderly close
2018-06-22T10:59:29.256Z socket.io:client client close with reason ping timeout
2018-06-22T10:59:29.257Z socket.io:socket closing socket - reason ping timeout
```
`engine:polling transport not writable - buffering orderly close` <-- I have not seen this line before, and not sure how it gets there: https://github.com/socketio/engine.io/blob/master/lib/transports/polling.js#L375

If you can reproduce this locally, i'd suggesting debugging around that code above.

**Comment by lolmaus** [comment]
Upgrading `ember-cli` and `testem` to latest releases didn't help.

But I've found the cause of my issue! It is setting the amount of `ember-exam` partitions (parallel test runs) to a number larger than the amount of CPU cores available on the CI. I assumed that extra partitions would be queued (I still think they should).

**Comment by kategengler** [comment]
I encountered the `Lost UI shared context` variant of this today after upgrading a 3.0 app to 3.2(ish), when running on CircleCI (2.0), also with `ember-exam`. 

I tried many of the suggestions in this thread, and what did work was removing the `partition`/ `parallel` option to `ember-exam`. 

Ember 3.2.0
ember-cli 3.2.0-beta.2
testem 2.8.2

**Comment by segl84** [comment]
Noticed headless chrome to run tests much slower than regular chrome. Further research led me to https://github.com/Codeception/CodeceptJS/issues/561.

Adding `--proxy-server='direct://'` and `--proxy-bypass-list=*` to the list of browser_args in the testem configuration seems to have solved the initial timeout problem for me.

**Comment by bryanaka** [comment]
I also noticed by turning `JOBS=2` On circleci cleared up the issue I had completely. 

I thought this only impacted build but apparently the problem can leak into tests somehow.

**Comment by Frozenfire92** [comment]
Thought I would chime in as another victim to this bug

I also encountered the `Lost UI shared context` issue on CircleCI (v1) only. We also use ember exam with 2 circle containers

It started occuring after upgrading to 3.3 from 3.1

What fixed it for me was the combination of adding `--proxy-server='direct://'`, and `--proxy-server='direct://'` to browser_args, as well as increasing the timeout to 30 seconds

If it reoccurs I will try setting circleci env variable `JOBS=2` and report back

**Comment by stefanpenner** [comment]
With https://github.com/testem/testem/pull/1283 we have correct the error message for when the total test suite time has been reached...

Released as v2.9.1.

Some subset of you timeouts are due to that, and this error message should help track those down.

**Comment by step2yeung** [comment]
@leondmello you can check your `package-lock.json` or `yarn.lock file`

**Comment by ming-codes** [comment]
@step2yeung Going over testem's code, it seems like testem tries to terminate the process immediately after receiving `after-tests-complete`. This could explain why the socket is disconnected unexpected. Shouldn't testem tries to clean up the socket before terminating the process?

**Comment by allthesignals** [comment]
I'm also seeing this error regularly at random times. Sometimes it will switch from that to `RuntimeException: Found equal nodes with different coordinates`, an error which only appears in Firefox and one which I can't find any information on (I've never heard of it).

**Comment by step2yeung** [comment]
@ming-codes When you say "disconnected unexpectedly", can you point to which error in the code? (Want to make sure we are talking about the same one) Would you have any examples of the lack of cleanup causing the error? 

But I do agree we might want to do socket cleanup before terminating the process.

@allthesignals this error being..?
Definitely first time seeing `RuntimeException: Found equal nodes with different coordinates`. Doesn't seem like that is coming from Testem, what is throwing that error?

**Comment by allthesignals** [comment]
@step2yeung "Browser timeout exceeded: 10s" - the other one I've learned is unrelated.

**Comment by stefanpenner** [comment]
Interesting @alexscarlett can you share a reproduction?

**Comment by NullVoxPopuli** [comment]
@stefanpenner my app is a reproduction https://github.com/NullVoxPopuli/emberclear/
but, I'm not sure where this is happening. I have event listeners in multiple places.
The only way I can run my tests at a reasonable pace is in headless

**Comment by stefanpenner** [comment]
@step2yeung if you have time, mind investigating ^^ ?

**Comment by step2yeung** [comment]
@NullVoxPopuli Can you share some reproduction steps to reproduce the error?
Steps i taken so far:
```
git clone https://github.com/NullVoxPopuli/emberclear.git
cd emberclear/packages/frontend
yarn install
ember build
ember test --path=dist 
```
And I have been unable to reproduce the timeout. Are you able to get a consistent reproduction of the problem?

**Comment by alexscarlett** [comment]
@step2yeung hey there, I do get the `browser timeout exceeded` error everytime, but it states a different test as the problem every run. seems to be arbitrary

**Comment by NullVoxPopuli** [comment]
@step2yeung I usually just do `yarn start:dev` and then visit https://localhost:4201/tests
Thanks for looking! :D

**Comment by step2yeung** [comment]
@NullVoxPopuli Apologies. What I meant was ran the test suite multiple times, within the 30 minutes I've spent, I did not get a `browser timeout exceeded`. The average time of the test suite for me is ~80-90 seconds.

**Comment by NullVoxPopuli** [comment]
hmm, maybe something is wrong with my computer then :(

**Comment by step2yeung** [comment]
@NullVoxPopuli Just ran the tests with `yarn start:dev` and hitting `http://localhost:4201/tests`. 
I'm not sure if this is the issue, but it seems like there is some callback that's not returning (or returns much much later), causing the test to just stay there and wait.

![screen shot 2018-12-20 at 9 36 15 am](https://user-images.githubusercontent.com/9669889/50301341-ea2e5f80-043b-11e9-80d2-e2beba2d2d02.png)

~a minute later, the test decided that it passed. And this was true for more than 1 test:
![screen shot 2018-12-20 at 9 43 41 am](https://user-images.githubusercontent.com/9669889/50301372-fca89900-043b-11e9-94cc-75ab2ed050c0.png)

This also leads to some test failing for 60s timeout that is a default for qunit:
![screen shot 2018-12-20 at 9 44 49 am](https://user-images.githubusercontent.com/9669889/50301390-0af6b500-043c-11e9-9a0c-e727ca732a83.png)

Something there definitely is fishy, since I don't expect the simple tests to have that long of a wait. Although I have yet to see the `browser timeout exceeded` this might be somewhere you want to explore.

**Comment by NullVoxPopuli** [comment]
is there a way to list everything that ember/qunit is waiting on? like, for every test, log outstanding timers or something? I could track that down, and report back after some investigating

**Comment by step2yeung** [comment]
@NullVoxPopuli The latest version of ember-qunit (4.2.0) added test-isolation that may help with this: https://github.com/emberjs/ember-qunit/blob/master/TEST_ISOLATION_VALIDATION.md

**Comment by thec0keman** [comment]
Is it possible this could be also triggered by memory?  We have an Ember test suite with over 3000 tests, and several hundred of them are acceptance tests.  We've been seeing this timeout error sporadically when running the whole suite in a single travis instance, but splitting the suite into multiple travis runners seems to have helped.

**Comment by snewcomer** [comment]
Recently updated to ember-cli 3.6 and saw this error on our Jenkins setup (node 8.11).  Have tried a wide variety of recommendations but no go yet.

**Comment by brandynbennett** [comment]
I get `Error: Browser timeout exceeded: 10s` randomly when using `ember exam --split=2 --parallel` in CircleCi. When I go back to plain `ember test` it works consistently.

**Comment by brandynbennett** [comment]
Happened when setting browser time to 500 as well.

**Comment by brandynbennett** [comment]
Was able to get mine fixed by moving to the latest version of ember-gestures (1.1.1) There was a memory leak there that was causing Chrome to run out of memory and thus the socket disconnected.

**Comment by snewcomer** [comment]
Yeah I guess it makes sense it is in the dependency graph somewhere.  I'm sure it varies for many people.  Will keep digging!

**Comment by scottkidder** [comment]
I'm currently on ember-gestures 1.1.1 and still seeing these issues. I'm quite certain there is some useful information to be had by using https://github.com/emberjs/ember-qunit/blob/master/TEST_ISOLATION_VALIDATION.md but I haven't had time to dig into it quite yet.

**Comment by scottkidder** [comment]
:tada: Using qunit test isolation and the stack traces it provides in the console I believe I have tracked my issues down to some leaky async in ember-cli-loading-slider. :crossed_fingers:

**Comment by lolmaus** [comment]
@scottkidder The file you linked to is unavailable. Can you please update the link?

**Comment by patocallaghan** [comment]
@lolmaus Looks like the link is here now https://github.com/emberjs/ember-qunit/blob/master/docs/TEST_ISOLATION_VALIDATION.md

**Comment by bracke** [comment]
I have the same problem, except it seems to vary between platforms:

On OSX testing works without problem.
On Windows 10 Testem fails as described above.
Note: This is with the same projekt.

**Comment by raido** [comment]
Not sure if directly related this this but I have issues with Testem + Browserstack - where intermediately multiple browsers fail to connect and get timeout. On build rerun all browsers pass again.

**Comment by snewcomer** [comment]
This ultimately turned out to be a memory issue.  Our node instance was leaking the Ember App container.  After fixing, upgrading worked.  Related to this - https://github.com/emberjs/data/issues/5061

**Comment by stefanpenner** [comment]
@snewcomer that is usually what we see. I think we should consider a chrome-debugger-client runner for testem, so that we can get extra telemetry and provide better details when something goes sideways.

**Comment by GCheung55** [comment]
I was seeing timeout issues for the past week. Upon digging, I learned of this: https://bugs.chromium.org/p/chromium/issues/detail?id=960926

I somehow updated to Chrome 74 and began to see failures. Prior versions seems to be fine and Chrome 75 is supposed to have the fix - planned release is June 4th.
https://www.insightportal.io/news/all-news/chrome-75-release-date-and-features

If you're seeing a socket disconnected issue or browser timeout issue, check your Chrome version. I'm going to check Chrome 75 once it's out.

**Comment by stefanpenner** [comment]
I'm tempted to close this issue. As far as we are aware, timeouts and issues that originated from testem itself have been resolved. The rest are broader ecosystem issues.

@step2yeung / @patocallaghan thoughts?

**Comment by patocallaghan** [comment]
I'm happy to close the issue. Any timeouts I've found these days are not related to testem specifically but rather chrome or bad app/test code.

**Comment by patocallaghan** [comment]
Actually it may be worth collating some of the reasons why timeouts occur and adding them to the README to help others in future.

**Comment by stefanpenner** [comment]
@patocallaghan. Ya that’s a good idea, I don’t have much time though, if you happen to have free cycles would you mind starting that off?

**Comment by patocallaghan** [comment]
@stefanpenner I'll see if I can carve out some time this week to put something together

**Comment by amiel** [comment]
@patocallaghan Please update us here when you have something. I'm troubleshooting Browser disconnected in headless chrome right now and I look forward to your list of reasons why timeouts occur. Thanks!!!!

**Comment by BIMseven** [comment]
Has there been any word on this fix? The problem is still persisting in my team's environment

**Comment by lolmaus** [comment]
@BIMseven There's a chance it's caused by a nen leak in your tests.

There are many ways to create a mem leak that would not affect your users but would have your acceptance tests crash.

**Comment by shreyasawkar3595** [comment]
> 🎉 Using qunit test isolation and the stack traces it provides in the console I believe I have tracked my issues down to some leaky async in ember-cli-loading-slider. 🤞

How did you resolve this?

**Comment by amk221** [comment]
I realise this issue can arise many different ways. But, just in case this helps anyone - our app had a few hyperlinks that pointed to _outside_ the Ember app, which when clicked would leave Qunit. Fixing that helped solve the browser timeout issues.

**Comment by buschtoens** [comment]
I can confirm that what @amk221 describes was the main issue for us a well. A QUnit test helper that throws an error and fails the test, when any form of navigation occurs, would be sweet.

**Comment by scalvert** [comment]
We also had the same issue using faker to generate URLs, which would invariably be external. Overriding this behavior also helped stabilize our tests.

**Comment by kaermorchen** [comment]
I have catched the same issue when updated ember addon to embroider compatibility. The fix for me is changing in `./tests/dummy/config/environment.js` from `rootURL: '/ember-mdi/'` to `rootURL: '/'`

**Comment by runspired** [comment]
We are having this issue after upgrading from testem 3.4 to testem > 3.4. At first I thought it might be due to the socket.io change having caused chrome to care more about security permissions, but upon digging in I'm less convinced.

One thing I've noticed is the websocket never seems to get established, instead socket.io is persisting in polling mode which would be far more brittle and more likely to fail if a test was taking a while.

Bumping `'socket_heartbeat_timeout'` to `45` seconds did not address this, though since we're (for unknown reasons) using polling instead of sockets on more recent socket.io this config is perhaps meaningless? I'm unsure if it is applied to the polling timeout as well.

**Comment by kategengler** [comment]
@runspired Is the message the exact same as in the issue? "Browser failed to connect..."? If so, does increasing `browser_start_timeout` have any effect?

**Comment by runspired** [comment]
@kategengler yes, and I've increased it without any success. I've been digging in to the engine.io/socket.io logs and I increasingly think engine.io has recent changes that are suspect. The socket crashes fairly regularly and not due to timeouts, leading it to fall back to polling, re-establish the socket and repeat the error cycle.

**Comment by runspired** [comment]
We've traced this down to these changes https://github.com/socketio/engine.io/compare/3.5.0...3.6.0

Specifically: https://github.com/socketio/engine.io/commit/58e274c437e9cbcf69fd913c813aad8fbd253703

It appears the new default of 1MB instead of 100MB for maxBufferSize is not enough for many test setups. We'll need to either set this config in testem or provide a way for users to pass engine.io/socket.io config from the testem config.

**Comment by runspired** [comment]
Looks like `socket_server_options` (not documented) is the answer

```ts
 let ioOptions = {};
    if (this.config.get('socket_server_options')) {
      ioOptions = this.config.get('socket_server_options');
    }
```

**Comment by johanneswuerbach** [comment]
Happy to make the 100MB a default again as DoS by malicious clients shouldn't really be an issue for testem.

**Comment by ahemed-haneen** [comment]
> It would be great to get the chrome debug console output in those cases, maybe using the remote debugger are somehow manually.
> 
> Looks like in some cases the initial connect takes >30s with can have multiple reasons: unparsable js, slow js parsing, failed websocket, testem client bug, etc.
> 
> Sadly there isn't much, which can be done before connecting (as there is obviously no connection), but maybe the remote debug protocol could provide some access to the console output

I'm starting to experience this after adding large js files into my code base. 
and no matter how much i increase browser time out the issue still seems to persist. 

Have you found out any solutions or anything which i can use to debug the issue atleast?

**Comment by chbonser** [comment]
@runspired I have a couple of products which are suffering from timeout intermittency on the CircleCI. The browser log includes the following which max me suspect it is related to your engine.io [theory](https://github.com/testem/testem/issues/1021#issuecomment-1186605445)

> Error: Browser timeout exceeded: 10s
> ....
> [1114/112319.898905:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /host/run/dbus/system_bus_socket: No such file or directory [.... much more here ... ]

Is this a similar error to the one you were debugging? 

I'm using `engine.io@6.2.0` I tried various older versions of engine.io and either still see the error (6.1.x) or things break worse (3.5.0).

**Comment by bantic** [comment]
We ran into this as well, and we also concluded that it's the socket.io `maxHttpBufferSize` default change from 100MB to 1MB that is the culprit (as noted here: https://github.com/testem/testem/issues/1021#issuecomment-1186605445).

I dug into this a little bit, and this is what I believe is happening:
  * During a CI run, the socket.io connection is upgraded from long-polling to a websocket transport
  * Sometime later, something results in the Testem socket.io client (within the iframe) attempting to emit a message that's greater than 1MB in length -- this could be a massive test result (with many assertions), or just a very-large console.log, for example
  * The WebSocket transport is defined w/ a `maxPayload` (docs [here](https://github.com/websockets/ws/blob/master/doc/ws.md#new-websocketserveroptions-callback)) of 1e6 (1MB), which comes from the socket.io `maxHttpBufferSize` default of 1e6 ([docs here](https://socket.io/docs/v4/server-options/#maxhttpbuffersize) -- the `maxHttpBufferSize` is passed directly, as `maxPayload`, when instantiating the WebSocket Server)
  * the websocket connection is closed (by the server, I think) because the payload is too large
  * at that point, the Testem server detects the disconnect and starts a reconnect timer ([here](https://github.com/testem/testem/blob/0bd05cec7f83bfe9f2e10ddfab54556d724ee179/lib/runners/browser_test_runner.js#L262-L268))
  * at the same time, socket.io attempts to automatically reconnect using the long-polling transport
  * the reconnect succeeds, but the Testem server isn't aware of it (notes on this below) and, eventually, the reconnect timer goes off and the suite fails with the "Browser timeout exceeded" issue


Why isn't the Testem server aware of the disconnect?
I think this is because it's not correctly listening for the "reconnect" event. The client listens for "reconnect" in testem_connection.js [here](https://github.com/testem/testem/blob/0bd05cec7f83bfe9f2e10ddfab54556d724ee179/public/testem/testem_connection.js#L186-L188).
At the time that the reconnect listener was added (https://github.com/testem/testem/pull/1340), Testem used socket.io v2.x. But in the interim, socket.io has been upgraded to v4.x, and in the [v2->v3 socket.io migration guides](https://socket.io/docs/v4/migrating-from-2-x-to-3-0/#the-socket-instance-will-no-longer-forward-the-events-emitted-by-its-manager) they point out that the "reconnect" event is no longer forwarded:
The code that does `socket.on('reconnect` in Testem should be `socket.io.on('reconnect`, I believe.
With a local debug copy I confirmed that the 'reconnect' event is only encountered if using `socket.io.on`, but I didn't manage to fix the reconnection code even after making that change -- I think perhaps the sequence of events that are sent doesn't work out to correctly "restart" the Testem server's awareness of the CI suite.


**TLDR**: The socket.io websocket transport will drop its connection if a large message is emitted by Testem. Socket.io _does_ reconnect, but due to (I think) a bug in the Testem reconnect-detection code, Testem thinks the browser is gone and throws the "Browser timeout exceeded" error after `browser_disconnect_timeout`.


I put together a minimal reproduction. In essence, it is just creating a 1MB-sized `console.log` message and logging it -- this triggers the WS close and the un-detected reconnection and ultimately the "timeout exceeded" error.

https://github.com/testem/testem/pull/1845
